spring:
  datasource:
    url: jdbc:mysql://localhost:3306/invoice_management_db
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: update
    dialect: org.hibernate.dialect.mysql5dialect
    show-sql: false
    properties:
      hibernate:
        format_sql: true

application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 20000
      refresh-token:
        expiration: 604800000 # 7 days
